---
booktitle: Proceedings of the 1st Machine Learning for Healthcare Conference
volume: 56
year: '2016'
start: 2016-08-18
end: 2016-08-19
published: 2016-12-10
shortname: MLHC
layout: proceedings
series: Proceedings of Machine Learning Research
id: MLHC-2016
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
sections: 
editor:
- given: Finale
  family: Doshi-Velez
- given: Jim
  family: Fackler
- given: David
  family: Kale
- given: Byron
  family: Wallace
- given: Jenna
  family: Weins
description: |
  Proceedings of the 1st Machine Learning for Healthcare Conference
    Held in Northeastern University, Boston, MA, USA on 18-19 August 2016

  Published as Volume 56 by the Proceedings of Machine Learning Research on 10 December 2016.

  Volume Edited by:
    Finale Doshi-Velez
    Jim Fackler
    David Kale
    Byron Wallace
    Jenna Weins

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 18--19 Aug
url: http://proceedings.mlr.press
baseurl: "/v56"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v56
bibtex_copy: true
endnote_copy: true
apa_copy: true
email: ''
conference:
  name: Machine Learning for Healthcare Conference
  url: http://mucmd.org/conference-2016.html
  location: Northeastern University, Boston, MA, USA
  dates:
  - 2016-08-18
  - 2016-08-19
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v56.bib
